name: Deegram2

on:
    push:
    workflow_dispatch:
    
jobs:
  deploy-bot:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name abhishekhbhootwala
           git config --global user.email abhishekbhutwala5@gmail.com
           git config --global credential.helper store
           echo "https://abhishekhbhootwala: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@github.com" > ~/.git-credentials
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone https://github.com/abhishekhbhootwala/Deegram2
       - name: Running Deegram2
         timeout-minutes: 350
         continue-on-error: true
         run: |
           sudo sh mbot.sh
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/abhishekhbhootwala/Deegram2
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop $(date -u +%D-%T%P)"
              git push -q https://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@github.com/abhishekhbhootwala/Deegram2 HEAD:main
